### ISSUE TITLE
Lenok and redmi 8 wont pair/sync

### ISSUE THREAD

**Issue by J0SH1X** [AsteroidOS/AsteroidOSSync#100]
if i open the asteroidos sync app and pair my watch my phone will ask me to pair it without a need to enter a pin afterwards a 2nd pair popup comes up and asks for a pin then after a minute the connection to my watch is dropped and will never be able to connect again

**Comment by jrtberlin** [comment]
Sorry to hear that. 
I have a few questions:
Which AsteroidOS version are you using?
What's the version of AsteroidOSSync?
Are you using a custom rom on your redmi 8?
What is the Android version of your redmi?
Has this worked prior?

**Comment by J0SH1X** [comment]
well , you can close this iusse ive got it to work by deleting the android wear app, sadly i had to return to AW as asteroidos not not ready enough for me

**Comment by jrtberlin** [comment]
Thanks for letting me know!
