### ISSUE TITLE
Find Alternative to SweetBlue

### ISSUE THREAD

**Issue by jrtberlin** [AsteroidOS/AsteroidOSSync#101]
[SweetBlue](https://github.com/iDevicesInc/SweetBlue), the BLE library we use, is deprecated.
SweetBlue v3 is expensive, [proprietary and closed source](https://sweetblue.io/docs/FAQ_V3). 
Although the code has some entertaining value (unnecessary code, code styling issues, deprecated APIs all over the place,...) I don't have any sentimental thoughts about it and **we should replace it**.

We have the following options:
- **Search** for a maintained library with a similar feature set (I haven't found one yet)
- **Write** and maintain our own library (a lot of work)
- **Fork** [the library](https://github.com/iDevicesInc/SweetBlue) and maintain it (headaches and entertaining code reviews included)
- Use the **native Android BLE stack** ([not a great option](https://github.com/iDevicesInc/SweetBlue/wiki/Android-BLE-Issues))

I think the best option would be to write a new library that uses the same interface to make it a 'drop-in' replacement.

**Comment by jrtberlin** [comment]
It seems like [RxAndroidBle](https://github.com/Polidea/RxAndroidBle) could be a replacement. However, the interface design and the scope of the lib differ from SweetBlue and changes scattered through AsteroidOSSync are necessary.

**Comment by FlorentRevest** [comment]
This looks great! I guess that no matter what lib we find we will have to change code scattered through AsteroidOSSync.

**Comment by jrtberlin** [comment]
My idea would be to implement our own `BleManager` with a similar interface and call the new library from there. This would have the benefit that we could keep the maintenance low with future changes to ble libraries and modularize the project a bit more.

**Comment by FlorentRevest** [comment]
Mhhh, I wonder if this would be the right abstraction... Maybe it is. Otherwise, SynchronizationService was meant to be an abstraction for the rest of the source code, I'm not sure whether we really ever managed to achieve this but well... :)

**Comment by jrtberlin** [comment]
I think [Nordics BLE library](https://github.com/NordicSemiconductor/Android-BLE-Library) might be a better fit for our application architecture. But we would have to find our own solution or [another lib](https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library) for device scanning.
