### ISSUE TITLE
Lenok will pair, but then loses connection and won't connect anymore

### ISSUE THREAD

**Issue by Bombatomba** [AsteroidOS/AsteroidOSSync#102]
Hi there,

I have just installed AsteroidOS (1.1-nightly) on my LG G Watch R Lenok and AsteroidOS Sync (version 0.14) on my Fairphone 2 (running on LinneageOS version 16.0-20200107-MicroG-FP2).
Directly after installing Sync, I can find my Lenok and connect to it. That seems to work for a short while: I can already fiddle with some settings within the Sync-app, before I have to enter a PIN (I'm not sure if that's supposed to be possible). After entering the PIN and clicking the ok-icon on the phone, the connection between the devices drops a few seconds later. Any attempt to reconnect is met with a message "cannot communicate with lenok". I tried it again a few minutes later, at wich point the message had changed to "cannot communicate with AA:AA:AA:AA:AA:AA", which might indicate an issue with the MAC-address. If I uncouple the device, the Lenok is still in my list of devices, but reconnection is again met with the fist message. I have already uninstalled Wear OS, as that seemed to have worked for J0SH1X in #100, but that didn't change anything for me.

Any idea what might cause this?

Kind regards,

Bombatomba

**Comment by jrtberlin** [comment]
@Bombatomba sorry to hear.
Does it work with the 1.0 stable release?

**Comment by Bombatomba** [comment]
> 
> 
> @Bombatomba sorry to hear.
> Does it work with the 1.0 stable release?

I thought of doing that, but I couldn't actually find that version anywhere. Could you point me in the right direction?

**Comment by jrtberlin** [comment]
> > @Bombatomba sorry to hear.
> > Does it work with the 1.0 stable release?
> 
> I thought of doing that, but I couldn't actually find that version anywhere. Could you point me in the right direction?

We haven't changed much on AsteroidOSSync for a long time, so I suspect it be either an issue with the nightly, your install or a Bluetooth issue specific to your android device.
**Here is the [AsteroidOS 1.0 - lenok](https://release.asteroidos.org/1.0/lenok/) build.**

**Comment by Bombatomba** [comment]
> 
> 
> > > @Bombatomba sorry to hear.
> > > Does it work with the 1.0 stable release?
> > 
> > 
> > I thought of doing that, but I couldn't actually find that version anywhere. Could you point me in the right direction?
> 
> We haven't changed much on AsteroidOSSync for a long time, so I suspect it to be either an issue with the nightly, your install or a Bluetooth issue specific to your android device.
> **Here is the [AsteroidOS 1.0 - lenok](https://release.asteroidos.org/1.0/lenok/) build.**

Thanks, I will try that!

**Comment by Bombatomba** [comment]
Okay, I installed 1.0 and that seems to have done the trick! The connection is now stable. The only thing is that I now encounter two new problems: 1. So far I can see in the music app on the watch what is playing in my Spotify app on my phone, but I cannot pauze it or go to the previous/next song. It could be that my phone is blocking that kind of access. 2. For some reason v1.0 is very unstable on my watch, if I remove the watch from the charger, is turns off / crashes every thime after about 15 secondes or less. This makes the watch quite unusable. But it isn't an AsteroidSync issue of course so I will take that issue elsewhere. Maybe just start with a reinstall.

**Comment by jrtberlin** [comment]
We had a small discussion on IRC and there was a recent change in the Bluetooth baudrate. 
You can edit `/lib/systemd/system/patchram.service` on your watch and remove `--baudrate 3000000` from the ExecStart line to revert this change.
Does that improve the situation on the latest nightly?

**Comment by Bombatomba** [comment]
> 
> 
> We had a small discussion on IRC and there was a recent change in the Bluetooth baudrate.
> You can edit `/lib/systemd/system/patchram.service` on your watch and remove `--baudrate 3000000` from the ExecStart line to revert this change.
> Does that improve the situation on the latest nightly?

Okay, so I just installed the latest 1.1, this time from an Ubuntu-pc. For some reason the watch spammed my phone with 5 different verification numbers / PINs in a row, but after one sequence of it connecting-disconnecting-connecting, it now seems to have normally connected withoud issue. I'm not sure what caused this change, but for now I will keep the current settings and see if the connection remains stable. If not, I will try your proposed method. In any case, thank you very much for your help and your time!

**Comment by jrtberlin** [comment]
Great to hear! If it stops working, just comment and I reopen the issue.
