### ISSUE TITLE
App is crashing after connecting to watch.

### ISSUE THREAD

**Issue by KorakSilvercloud** [AsteroidOS/AsteroidOSSync#11]
The app will connect to the watch then after a few seconds it will crash and close out. If you open it back up it will connect back to the watch for a few seconds before crashing again. I am including what looks like relevant part of the log.

[CrashLog.txt](https://github.com/AsteroidOS/AsteroidOSSync/files/911389/CrashLog.txt)

**Comment by FlorentRevest** [comment]
Thanks for reporting, should be fixed by https://github.com/AsteroidOS/AsteroidOSSync/commit/dc1c1159e86b9713a063bd8b491eaf67fc4c887e
