### ISSUE TITLE
Suggestion: Step Counter

### ISSUE THREAD

**Issue by Drakador** [AsteroidOS/AsteroidOSSync#112]
Having a step counter would be incredibly beneficial to Asteroid OS. I often enjoy hiking and gauge part of the exercise I got from the steps, alongside whatever I need to do later in the day after I am done with work. It could easily fit just below the weather icon in the events and weather screen, or above the battery level indicator in the top screen.

**Comment by Drakador** [comment]
Opened this in the wrong Repo

**Comment by jrtberlin** [comment]
Sorry, for the late reply. We had the same [feature request](https://github.com/AsteroidOS/asteroid/issues/134) at the asteroid repo. I think it makes more sense to track the progress there. It doesn't seem like GitHub has the ability to merge issues, so I'm closing this one.
