### ISSUE TITLE
[FEATURE REQUEST]Possibility to make upgrading watch's OS easier

### ISSUE THREAD

**Issue by issu-shooter** [AsteroidOS/AsteroidOSSync#120]
Can the SYNC app check AsteroidOS's repo and download newest images, then flash it to the watch when connected to the watch (wireless or physical)? I remember it's possible to use an Android device to adb/fastboot another android device.
Taking a step forward, can there be a script built inside AsteroidOS that can do automatic updates without having to stay connected to the phone, only have to let the Sync app/computer push the file in, then the watch will automatically? Or a desktop app that will do this job?

Maybe this needs a huge amount of work and can never be achieved in a short period, but never mind, this is just some idea.

**Comment by jrtberlin** [comment]
We have a working package manager. Downloading whole images seems a bit overkill. The watch needs a forwarded internet connection or the packages that have changed.
Update solutions are discussed here: https://github.com/AsteroidOS/asteroid/issues/47
