### ISSUE TITLE
Instead of starting over with a custom sync app, use KDE Connect instead.

### ISSUE THREAD

**Issue by TheOPtimal** [AsteroidOS/AsteroidOSSync#123]
For those of you who don't know, KDE Connect is a KDE Application to connect devices together. It supports plugins for extra functionality.

Now, even if you know what KDE Connect is, you may not know that it can connect ANY KDE Connect enabled device to ANY KDE Connect enabled device, which is powerful. It's not limited to connecting Computer and Phone, for example you could connect your work phone to your personal phone, your tablet to your phone, your laptop to your PC, etc.

KDE Connect has an Android (Java version), Desktop (Qt) version, and a Linux Mobile (QML) version. We could take the QML version and port it to Asteroid OS and have somethign very powerful without have to start from scratch on a sync app. This would also allow for connecting a watch to anything, A Linux or Android mobile, a tablet, laptop, PC - Anything that supports KDE Connect.

Plus, it supports plugins, which could allow for adding in watch-focused features into the app.

Also, because a QML version already exists porting would be minimal effort really.

If you're asking for call support, that could just be done with bluetooth. KDE Plasma already does this when a phone is connected to the desktop, so some of that code could be taken a look at and ported to AsteroidOS.

KDE Connect also create an ecosystem that doesn't lock you in, because it isn't limited to just one device/OS. There are attempts to port it to Windows/Mac aswell.

**Comment by jrtberlin** [comment]
Hi, thank you for looking into this.
KDE Connect is great. However, not all of our watches have built-in WiFi so our solution must support a Bluetooth connection. 
So I don't think it is a good fit for us, but we could reuse some of their code for sure.

**Comment by TheOPtimal** [comment]
https://www.reddit.com/r/linux/comments/6ggb36/kde_connect_works_over_bluetooth_now_please_help/
https://www.omgubuntu.co.uk/2017/06/kde-connect-bluetooth-backend-development

KDE Connect supports bluetooth, it just needs to be enabled at compile-time using the CMAKE_BLUETOOTH_ENABLE switch.

**Comment by jrtberlin** [comment]
#127 is merged so the main issue we have that would require a rewrite is gone.
