### ISSUE TITLE
Feel free to add support into Gadgetbridge and use it as your companion app

### ISSUE THREAD

**Issue by vanous** [AsteroidOS/AsteroidOSSync#124]
Hey all,

great effort and a very long road ahead. I know you are aware, let me only mention that adding support for AsteroidOS into [Gadgetbridge](https://codeberg.org/Freeyourgadget/Gadgetbridge/) (do note the Codeberg link), should be pretty straight forward, as far as i can see. We have many issues already solved, like persistent connection, preferential notifications per app with keyword based rules, data fetching, firmware updates, weather, activities and workouts... And, we also have many open issues and tons of room for improvements and would therefore prefer cooperation over private fork :). At this point, non of us uses AsteroidOS watches, so there has been no-one to add support yes but the process is straight forward and documented [here](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/New-Device-Tutorial). Gadgetbridge does not have any network access, the idea is that if that need comes a companion app with safe data passing would need to be created, weather notifications already work this way. To see some screenshots, you can check articles in [this device]( https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Amazfit-Bip
), it is one of the most completely documented ones. 
Good luck and feel free to ask anything here or in our project i can try to answer here to the level of my understanding :)

**Comment by miathedev** [comment]
I took a look at gadget Bridge. If i understood the documenation correct - if we implement everything around the recommended BLE Gatt specification everything should work instant?

https://www.bluetooth.com/specifications/assigned-numbers/

If yes - we are doing that. In AsteroidOS/asteroid-btsyncd im currently implementing a Health Device Profile.
Thanks for your post. In GadgetBridge are some nice worksteps mentioned for testing against BLE profiles. This will help me a lot to speed up my process.

**Comment by vanous** [comment]
Please have a look at our [wiki](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/), the [New device tutorial](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/New-Device-Tutorial) tries to lay out the steps needed. Besides a bunch of commercial devices, we also have support for things like Bangle.js or the various firmware of PineTime, feel free to look at them.

And a small advice: Gadgetbridge, not GadgetBridge :)

**Comment by jrtberlin** [comment]
#127 is merged so the main issue we had that would require a rewrite is gone.
