### ISSUE TITLE
Automatically reconnect on Bluetooth disconnect

### ISSUE THREAD

**Issue by TheLastProject** [AsteroidOS/AsteroidOSSync#14]
I know this is a device problem, but it's something AsteroidOS could work around. Sometimes (and with that I mean quite often), my Android phone decides to kill the connection with all Bluetooth devices. My Bluetooth headset automatically reconnects, yet AsteroidOS switches to disconnected state and doesn't seem to try to reconnect. It would be great if AsteroidOS could automatically reconnect when this happens.

**Comment by FlorentRevest** [comment]
I don't think we can handle that from the watch (I've never seen anything related in BlueZ). However this is the kind of problems that is supposed to be handled by SweetBlue. https://github.com/iDevicesInc/SweetBlue/wiki/FAQ_Technical#how-is-reconnection-handled You may have a hardware-specific issue to report to SweetBlue then.

**Comment by TheLastProject** [comment]
I see this issue is still open. 0.5 seems to have fixed 99% of these cases for me. Closing this.
