### ISSUE TITLE
Time doesn't sync immediately

### ISSUE THREAD

**Issue by megamaced** [AsteroidOS/AsteroidOSSync#147]
Observed with Bass and Dory watches

Pair either watch with the app, the time does not synchronise. I must untick "Synchronise Time" and then a second later tick it again before time is synced

**Comment by aTr00per** [comment]
I observed the same with lenok. Sometimes the app also crashes when checking the time sync.

**Comment by MagneFire** [comment]
This should be solved by https://github.com/AsteroidOS/AsteroidOSSync/commit/049cd0f6c3562d3b74a21b71256b5bfd54009dc9. Which was included in version 0.22.
