### ISSUE TITLE
AsteroidOSSync 0.22 crash on /e/OS 0.23

### ISSUE THREAD

**Issue by Bombatomba** [AsteroidOS/AsteroidOSSync#162]
Hi there,

AsteroidOSSync version 0.22 crashes on my Fairphone 3+ (which is running/e/OS version 0.23). This happens consistently about 1 second after it has connected to my AsteroidOS watch (LG Watch Urbane (bass)). I've had the issue for a long time now. I don't know exactly when it started, so I'm unable to pinpoint in which version(s) this problem originated.  hadn't gotten around to trying to fix it before. Today I updated my watch and my phone in an attempt to remedy it, but unfortunately the problem persists.
Is there a way to send a crash report from the app so I can add more details?

Kind regards,

B

**Comment by jrtberlin** [comment]
Hi,
sorry to hear that you are having issues with the app. 
- What Android version are you using? According to the [/e/OS releases ](https://gitlab.e.foundation/e/os/releases/-/releases)0.23 exists for Android P (9),Q (10) and R (11).
- Have you tried to reinstall the app or to clean the app data?
- If you have ADB enabled, you can use `adb logcat > log.txt` to generate a log while you try to open the app. After the app crashes, you can stop the log with Ctrl+c.

**Comment by Bombatomba** [comment]
Hi,

- My phone is using Android version 10.
- I have tried to wipe all AsteroidOSSync app data and cache, and then removed and reinstalled it. Unfortunately to no avail.
- Thanks for the tip on how to create a log. I have just generated one where I recreated the crash a few times. Will post the log as a next message.

**Comment by jacobputnam** [comment]
I am also having this issue on my Google Pixel 4a and LG Watch Urbane.

**Comment by jacobputnam** [comment]
> I am also having this issue on my Google Pixel 4a and LG Watch Urbane.
apparently, what fixed it for me (for now) was just going into the bluetooth settings and having my phone forget the previously connected watch device and re-pairing it. i'm not sure if this will last, but it is working like it used to right now.

**Comment by Bombatomba** [comment]
> > I am also having this issue on my Google Pixel 4a and LG Watch Urbane.
> 
> apparently, what fixed it for me (for now) was just going into the bluetooth settings and having my phone forget the previously connected watch device and re-pairing it. i'm not sure if this will last, but it is working like it used to right now.

Dude, brilliant move! I hadn't thought of that, but it works for me too! Thanks! Sync now works beautifully for me. (With the exception of the screenshot function, for some reason, but I rarely use that anyway.) I'll close this thread.

**Comment by Bombatomba** [comment]
> 

Correction: the screenshot function works as well.
