### ISSUE TITLE
AsteroidOOSync v 0.23 

### ISSUE THREAD

**Issue by Pepa77** [AsteroidOS/AsteroidOSSync#171]
Hi, I updated to version 0.23 and it doesn't work on android 11, it won't connect to the watch at all

**Comment by jrtberlin** [comment]
Sorry that you are having issues. 
Can you please provide some additional info.

- Smartphone Model
- Watch Model
- Do you use the Stock ROM? If not, which custom ROM do you use?
- if you know how to acquire logs: can you post them please?

**Comment by Pepa77** [comment]
I'm sorry I didn't know it was needed 22 it worked without problems 23 it doesn't work at all it's a Doogee v20 model it's their official firmware which can be said to be almost pure Android

**Comment by eLtMosen** [comment]
Starting a test matrix here, i got some watches and can test Lineage 19.1/Android 12 and stock android 11.
Always doing the routine -> pair watch -> unpair watch -> delete AOSS storage and cache -> pair next watch -> etc.

|---|lenok|---|---|
|---|---|---|---|
|LOS 19.1|works|---|---|
