### ISSUE TITLE
Weather Library doesn't use HTTPS 

### ISSUE THREAD

**Issue by jrtberlin** [AsteroidOS/AsteroidOSSync#175]
The weather library we use still uses http instead of https.
Open weather map has disabled access via http.

We have the following options:
- patch the upstream lib
- replace the lib

Someone already made a PR upstream and nobody seems to be active on the project. It seems the kore reasonable option is to switch the library.

**Comment by MagneFire** [comment]
For reference, this is probably the PR https://github.com/code-crusher/EasyWeather/pull/10

**Comment by MagneFire** [comment]
Completed via: https://github.com/AsteroidOS/AsteroidOSSync/pull/181
