### ISSUE TITLE
Cannot grant mange files permission on LineageOS 20 (Android 13)

### ISSUE THREAD

**Issue by BigB84** [AsteroidOS/AsteroidOSSync#176]
Hi,

I use LineageOS 20 with microG.

I can't grant permission to AsteroidOSSync to allow manage files.
When I click button nothing appears.
This is problem because app wont pass me further...

I tried to search for something like `pm grant org.asteroidos.sync android.permission.SOMETHING_WITH_FILE`  but not worked.

Could you help me plase?
It doesn't need to be a solution, may be a workaround.

**Comment by jrtberlin** [comment]
Closing in favour of #173
