### ISSUE TITLE
[0.25] Weather data is not synced

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/AsteroidOSSync#179]
I could test on android 12 (Lineage 19.1) and was not able to sync weather data using 0.25.

Note,
Successfully adding the watch (tunny) to AOSSync only worked after i completely removed the app and rebooted.
When just updating from 0.24, (and wiping data/cache) the app would claim connection but did not actually trigger pairing.

**Comment by jrtberlin** [comment]
Duplicate of #175
