### ISSUE TITLE
[0.25] Can not grant permissions on Android 13

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/AsteroidOSSync#180]
https://twitter.com/APO_161/status/1589983426522025986
![grafik](https://user-images.githubusercontent.com/15074193/200823309-fb2c84da-940c-402c-8c7e-1c3e9a24ff43.png)

**Comment by LeOS-GSI** [comment]
I'm the developer of LeOS-GSI. It's LineageOS-20 based and full ungoogled, but with as special LeOS-MicroG version. 

Note: My LeOS doesn't allow any connection to any google server.

**Comment by MagneFire** [comment]
> I'm the developer of LeOS-GSI. It's LineageOS-20 based and full ungoogled, but with as special LeOS-MicroG version. 
> 
> Note: My LeOS doesn't allow any connection to any google server. 

Thanks for providing some information, can you also give some more insight on what happens?
Does the app crash when it "prompts" for the notification permission?
Also, a `logcat` of the wpp would be massively useful.

**Comment by LeOS-GSI** [comment]
![IMG_20221109_204943_128](https://user-images.githubusercontent.com/2726574/200927288-f80c97e2-4ff1-4ddc-b478-1f25657c2ec9.jpg)
![IMG_20221109_204938_023](https://user-images.githubusercontent.com/2726574/200927290-61ead496-0c3a-4ad2-a012-8d8de0032af0.jpg)


Please see attached screenshots. I'm not able to grand notification permission.
That without error message is while app first run setup
The other is when trying to give the permission via settings/apps/

**Comment by derEremit** [comment]
same thing here
Graphenos Android 13

I installed through f-droid

experiencing what is explained here:
https://blog.esper.io/android-13-sideloading-restriction-harder-malware-abuse-accessibility-apis/

**Comment by derEremit** [comment]
and after re-reading the link I posted above, this is a workaround:

"These restrictions are tied to a new permission in Android 13 called ACCESS_RESTRICTED_SETTINGS. This permission controls whether or not the user can enable an app’s accessibility service. When an app has been sideloaded using the non-session method, ACCESS_RESTRICTED_SETTINGS is first set to “deny”. After viewing the “restricted setting” dialog, ACCESS_RESTRICTED_SETTINGS is set to “ignore.” At this point, the user can go to the app info page for the app in question, tap the three-dot menu, and then tap “allow restricted settings” to unblock access to the accessibility service. The user will then be asked to authenticate themselves, and if they pass, ACCESS_RESTRICTED_SETTINGS will be set to “allow” for the app. The system does not tell the user they can do this, but this could change in future Android 13 builds."

**Comment by jrtberlin** [comment]
Some additional info: https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/permission/Permissions.md#restricted-permissions

**Comment by eLtMosen** [comment]
Fixed at least in 0.28

**Comment by duhrer** [comment]
Same problem on Android 13 (as distributed by FairPhone) with 0.29.  I had to use the instructions in the [blog post](https://www.esper.io/blog/android-13-sideloading-restriction-harder-malware-abuse-accessibility-apis) before I could grant the required permissions and continue the process.
