### ISSUE TITLE
weather still no synchronizing

### ISSUE THREAD

**Issue by imlinstress** [AsteroidOS/AsteroidOSSync#184]
Despite the latest update, still facing the issue with the weather app. LineageOS 19.1.

**Comment by eLtMosen** [comment]
Hello @imlinstress and thanks for reporting!

I am also on the last available LOS 19.1 update before LOS 20. 
But for me, weather sync works using the 0.26 version of the AOSSync App. 
When did you last update/flash your watch? Afaiu, there have been changes to the weather sync on the watch side in recent month.

**Comment by imlinstress** [comment]
I flashed it in january the 2nd. It was the first time i heard about this amazing effort to create this OS.
From here wanna thank you and all the contributers for the work and especially for not giving up.

**Comment by eLtMosen** [comment]
Not giving up is easy in this case, working on AOS is just very much fun. Especially given nice folks turn up regularly and help out!

The change to weather sync on the phone side sure predate your flash. So, are not relevant here.
I can only give the usual drill advice to try unpair the watch, remove its device from Android BT settings, clear app data and cache in AOSSync app (done in the android settings app section). Then reboot both devices and see if the problem persist.
If so, we at least ruled out the obvious and someone with better Android debugging skills might chime in.

**Comment by imlinstress** [comment]
It works!!!
Thanks a lot for the instructions.
