### ISSUE TITLE
Feature wish: AsteroidOSSync to sync Watch Calendar to Phone Calendar

### ISSUE THREAD

**Issue by 2Belette** [AsteroidOS/AsteroidOSSync#19]
Would be very nice to have Asteroid on the watch to sync with Calendar on the phone.

Not specially with Android Stock Calendar, for example with [Calendar](https://f-droid.org/repository/browse/?fdfilter=calendar&fdid=com.simplemobiletools.calendar) on Fdroid as it is possible to use it without any external services and where it is possible to import .ics

**Comment by Rudloff** [comment]
I think it would be nice to use the [Calendar Provider API](https://developer.android.com/guide/topics/providers/calendar-provider.html) which is the standard way to store calendars on Android.
It would make compatible with every application that use this API (Google Agenda, DAVDroid, etc.).

**Comment by fizzgig242** [comment]
This is a main feature that is missing in Asteroid OS.
