### ISSUE TITLE
The Spanish translation does not take effect,

### ISSUE THREAD

**Issue by Caballlero** [AsteroidOS/AsteroidOSSync#20]
After compile AsteroidOSSync spanish Is not being shown

**Comment by FlorentRevest** [comment]
Indeed, I did not review your pull request https://github.com/AsteroidOS/AsteroidOSSync/pull/18 well enough and didn't notice you just paced a random file in a random dir. Please sene a new PR using a correct directory https://github.com/AsteroidOS/AsteroidOSSync/tree/master/app/src/main/res or use weblate...

**Comment by Caballlero** [comment]
ok
