### ISSUE TITLE
Dissable "battery optimization"

### ISSUE THREAD

**Issue by KorakSilvercloud** [AsteroidOS/AsteroidOSSync#29]
App should request to be excluded from battery optimization. I noticed notifications would not come to my watch if phone was asleep. Once I woke the phone they would all sync. 

I found the setting in the OS and told it to allow the app to run all the time and this fixed the issue.

**Comment by FlorentRevest** [comment]
This seems to be related to the "Doze" mode introduced in Android 6. Details at https://developer.android.com/training/monitoring-device-state/doze-standby.html

Our use case seems to be listed as "acceptable" but still requires manual interaction from the user. The following intent should be triggered: https://developer.android.com/reference/android/provider/Settings.html#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS after checking PowerManager.isIgnoringBatteryOptimizations() at https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/MainActivity.java#L87

Pull requests welcome.

**Comment by rizal-rovins** [comment]
Check my pull request

**Comment by FlorentRevest** [comment]
@rizal-rovins : Sorry for the short delay, I was kept busy by other things recently.

Thanks a lot for your great work ! Let me know if there is any problem validating the hacktoberfest task.
