### ISSUE TITLE
Is Bluetooth Low Energy Mandatory?

### ISSUE THREAD

**Issue by Technohacker** [AsteroidOS/AsteroidOSSync#32]
Hello all,
I tried running the sync app on my phone (quite old, no BLE support). My watch (tetra) connects on Android Wear normally, but AsteroidOSSync fails to find my watch (recently received a backported BT subsystem). Is BLE mandatory for connecting my watch to my phone?

Thanks!

**Comment by FlorentRevest** [comment]
Hi Technohacker,
Unfortunately, every AsteroidOS sync profile is based on Bluetooth Low Energy so it's currently mandatory to have a phone that supports BLE.

**Comment by Technohacker** [comment]
Aww man :\
Is it possible to add support later on? I can manage with another phone for now, but just to know :)

**Comment by FlorentRevest** [comment]
I definitely have no plans for traditional Bluetooth profiles. This would also be a lot of work only to support legacy devices

**Comment by Technohacker** [comment]
Yeah, I understand. Thanks for the response :)

**Comment by Wendigogo** [comment]
It's mandatory to have a phone that supports BLE and an AsteroidOS port that support it too (swift here). 😇

Your presentation at Toulouse is over @kodi?

**Comment by FlorentRevest** [comment]
Wendigogo: my nickname is kido not kodi. Presentation is next week and this is not the appropriate thread to discuss the presentation. ;)
