### ISSUE TITLE
Notification content

### ISSUE THREAD

**Issue by Rudloff** [AsteroidOS/AsteroidOSSync#34]
Hello,

When a notification has a text content (e.g. the content of a message), AsteroidOS does not display it:
![screen2](https://user-images.githubusercontent.com/840125/32700257-d1f25338-c7c2-11e7-842a-9a11bb0091d9.png)
![screen](https://user-images.githubusercontent.com/840125/32700258-d3286a26-c7c2-11e7-8eba-1e0462615689.png)

**Comment by FlorentRevest** [comment]
Unfortunately, the notification format on Android is not always standard.

This sometimes work, you gave an example here yourself: https://user-images.githubusercontent.com/840125/32700104-92391ecc-c7c0-11e7-9101-9746afd42e1d.png
But sometimes it doesn't, as underlined here.

If someone is willing to investigate the issue on various problematic notifications, the magic should happen here: https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/services/NLService.java#L142
For example, gadgetbridge does this a bit differently in https://github.com/Freeyourgadget/Gadgetbridge/blob/2f443ad41989c5326121b3f4d64ce88a2dad0730/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java#L269
It should be worth giving this a try.

**Comment by Rudloff** [comment]
The example you linked above was an e-mail without any content.
The content is also ignored in AsteroidOS:
![screen](https://user-images.githubusercontent.com/840125/32701191-58fb55d8-c7d1-11e7-9b9b-3fa759f7edc6.png) ![screen2](https://user-images.githubusercontent.com/840125/32701192-591fac6c-c7d1-11e7-8de2-6d9893f108a9.png)

It seems there three possible levels of text here:
![image](https://user-images.githubusercontent.com/840125/32701214-9b687072-c7d1-11e7-9763-52b51535146d.png)

**Comment by FlorentRevest** [comment]
Could you please try again with AsteroidOSSync 0.9 ? It should be available on F-Droid in the upcoming days.

**Comment by Rudloff** [comment]
I still get the exact same behavior with 0.10.
