### ISSUE TITLE
Launch on startup

### ISSUE THREAD

**Issue by Rudloff** [AsteroidOS/AsteroidOSSync#38]
Hello,
It would be nice to have an option to launch the app when Android starts, so we don't have to remember to launch it after a reboot.

**Comment by FlorentRevest** [comment]
This is a good idea. If anyone wants to contribute a patch for that, that would be welcome.

**Comment by Rudloff** [comment]
This feature works great, but is there any way to disable it? (I sometimes know I will not use my watch for several weeks.)

**Comment by FlorentRevest** [comment]
There is currently no way to disable it :/ Maybe for a future version, you can open a new issue.
