### ISSUE TITLE
Phone disconnects on application close

### ISSUE THREAD

**Issue by BakaOsaka** [AsteroidOS/AsteroidOSSync#42]
**Phone:** Pixel 2 XL
    Android 8.1.0 (OPM1.171019.013)

**Watch:** LG G Watch (Dory)
    Asteroid OS Alpha 1.0

**Application:** AsteroidOS Sync
    Version 0.8

Upon syncing my watch with my Android device via Bluetooth, the watch will work as intended, sharing messages, weather, time etc. as expected.
However, if I close the AsteroidOS Sync application (Recent Applications menu -> Swipe away) the watch will disconnect and stop communicating with the watch.
For comparison, with applications like Android Wear, if the phone-side application is closed it will still run as a background service and continue to communicate with the watch.

**Comment by FlorentRevest** [comment]
Thanks for reporting BakaOsaka, this is not supposed to happen.

**Comment by FlorentRevest** [comment]
I finally got an Oreo phone and was able to fix various bugs caused by this version. They will be included in 0.11 which isn't scheduled for release yet. Keep an eye on F-Droid during the next few weeks or build asteroidossync yourself if you want to get those fixes quickly.
