### ISSUE TITLE
Google Maps notifications are not synchronised

### ISSUE THREAD

**Issue by Rudloff** [AsteroidOS/AsteroidOSSync#46]
Hello,

Google Maps can display notifications that show the next step in your itinerary:
![maps notification](https://user-images.githubusercontent.com/840125/38832563-3e2d99ca-41c3-11e8-8833-75595f9ed560.png)
Is there any way to display them in AsteroidOS?

**Comment by FlorentRevest** [comment]
That would be a very good addition indeed.
Do you know if there is any API to retrieve those notifications? From a quickk look, they don't seem to be "normal" system notifications.

**Comment by Rudloff** [comment]
I found [this question](https://stackoverflow.com/questions/41599826/android-notification-listener-and-google-maps) but no answer :disappointed: 

I also tried to have a look at logcat but did not find anything useful.

**Comment by FlorentRevest** [comment]
Interesting.
Indeed, ongoing notifications are currently ignored https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/services/NLService.java#L145 but we could make an exception for Maps.
