### ISSUE TITLE
new icon idea

### ISSUE THREAD

**Issue by 532910** [AsteroidOS/AsteroidOSSync#60]
current one:
![image](https://user-images.githubusercontent.com/14617699/48194130-34acbe80-e35d-11e8-8a43-f7b74ad2a278.png)

my suggestion:
![image](https://user-images.githubusercontent.com/14617699/48194172-4d1cd900-e35d-11e8-8eef-af422fa24a1f.png)

(just a 5 minutes gimp concept)

**Comment by FlorentRevest** [comment]
I am not against having more vivid colors but they should stay coherent with the Asteroid logo's colorscheme.
Regarding the glider shape, I find it hard to recognize the Asteroid logo on your suggestion. I played with this idea before but ended up prefering the full logo instead.
If you come up with other suggestions, feel free to add comments here. Otherwise, you can close this issue.

**Comment by c-e-p-x-u-o** [comment]
where can I get https://asteroidos.org/public/img/logo.png in svg?

**Comment by comradekingu** [comment]
@c-e-p-x-u-o Nice! I don't know that the gradient is "material design" valid, but i like it. How about angling the surrounding square on the tip like the white square in the original logo? I think that would help with recognition.

I think there was more 3D going on in the original, it has some depth to it, but that is probably down to the perfectly angled sides. Could try and angle it a little bit inwards towards a vanishing point too, but that is polishing.

**Comment by FlorentRevest** [comment]
It's just been brought to my attention that I never answered the question about the AsteroidOS logo in svg... Sorry for that. It is available from Wikimedia for instance https://en.wikipedia.org/wiki/AsteroidOS#/media/File:AsteroidOS_logo.svg

**Comment by 532910** [comment]
I'm not a designer, and I use Inkscape less than once a year. But I've redraw the logo and now it weights 5.6K instead of 41K (7.3 times smaler)
https://sergio.outerface.net/misc/AsteroidOS_logo_new.svg

**Comment by FlorentRevest** [comment]
Thank you, this is really neat

**Comment by 532910** [comment]
I'll draw my idea in svg later.

**Comment by comradekingu** [comment]
The structure of the white elements are lots on me, but I thought:

![asterioid2](https://user-images.githubusercontent.com/13802408/53567621-106d2b80-3b60-11e9-9127-c060fa59f528.png)
![asterioid](https://user-images.githubusercontent.com/13802408/53567622-1105c200-3b60-11e9-9bb1-f7bc8e5b894a.png)
![asterioid3](https://user-images.githubusercontent.com/13802408/53568252-c2592780-3b61-11e9-9c88-53d7e9ee6079.png)
![asterioid4](https://user-images.githubusercontent.com/13802408/53568251-c2592780-3b61-11e9-9d30-458724c33546.png)

**Comment by FlorentRevest** [comment]
@comradekingu I don't think I understand what you are trying to show

**Comment by comradekingu** [comment]
@FlorentRevest It was meant to show an arm looking at a watch.

**Comment by 532910** [comment]
Sorry, it doesn't look so.

**Comment by comradekingu** [comment]
Nothing to be sorry about.
