### ISSUE TITLE
Porting Request: AsteroidOSSync to iOS devices

### ISSUE THREAD

**Issue by pleft** [AsteroidOS/AsteroidOSSync#62]
As the title suggests, an iOS app for iPhone users would be great!

**Comment by FlorentRevest** [comment]
We already have support for notifications on iOS thanks to the work done by @zhalas on ANCS
https://github.com/AsteroidOS/asteroid-btsyncd/blob/master/ancs.cpp

**Comment by pleft** [comment]
Yeap it works! But it requires extra software on iPhone like BLE scanner to connect

**Comment by alexander-potemkin** [comment]
I wonder if notifications could be customized in that scenario? Like forward notifications from WhatsApp (for example) and not from anything else?

**Comment by zhalas** [comment]
> I wonder if notifications could be customized in that scenario? Like forward notifications from WhatsApp (for example) and not from anything else?

On a technical level, this would be possible, as the ANCS protocol supports querying application details. However, there are two main issues:
* someone would need to implement filtering on the `btsyncd` side
* someone would need to implement filtering configuration. This should probably be handled by the companion app, as configuring it directly on the watch would be cumbersome. There is no companion app for iOS though... Even if some sort of crude filtering configuration could be implemented on the watch itself, it would still need to be developed

Unfortunately, I’m no longer using any smartwatch, so I won’t be able to help with any of the above :(

**Comment by alexander-potemkin** [comment]
Thank you very much for sharing that! It's of great help!
