### ISSUE TITLE
Buttons don't fit screen

### ISSUE THREAD

**Issue by TheLastProject** [AsteroidOS/AsteroidOSSync#75]
I can't tell if this silence phone thing is on or not (Fairphone 2, Android 7.1.2, AsteroidOS Sync 0.12):

![image](https://user-images.githubusercontent.com/1885159/57215933-af922180-6fee-11e9-8157-1770b2076bad.png)

**Comment by jrtberlin** [comment]
We should probably wrap the [cardviews](https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/res/layout/fragment_device_detail.xml) in a scrollable layout type.

**Comment by FlorentRevest** [comment]
@TheLastProject thanks for reporting!
@jrtberlin yes
I would maybe also consider moving this connect/disconnect button to the top bar. Maybe also the Unpair button at the bottom.

**Comment by jrtberlin** [comment]
I would leave the FAB and add bottom padding instead. (As shown in the screenshot)

![Screenshot_20190506-180421_AsteroidOS_Sync](https://user-images.githubusercontent.com/14153182/57238579-06691c80-702a-11e9-911e-8299105e46a4.png)

But I would move the unpair button either in the Scroll view at the bottom or in a 3 dot menu, as unpairing is probably something you don't want to do unintentionally.

**Comment by FlorentRevest** [comment]
Moving the unpair button to a 3 dot menu would certainly be a good idea
