### ISSUE TITLE
Android Q housekeeping and discussion

### ISSUE THREAD

**Issue by jrtberlin** [AsteroidOS/AsteroidOSSync#77]
With Android Pie (9) there was the introduction of [AndroidX](https://developer.android.com/jetpack/androidx) as a replacement for the [support libraries](https://developer.android.com/topic/libraries/support-library). Android Q is (if you believe the annotations in Android Studio) the last version of Android that supports the use of support libraries. 

**What we have to/should do in my opinion:**
- Move to [AndroidX](https://developer.android.com/jetpack/androidx)
    - The [Material Intro Screen ](https://github.com/TangoAgency/material-intro-screen)wasn't updated in 3 years, but there is an [AndroidX fork](https://github.com/DreierF/material-intro-screen)
- Implement a [dark mode](https://developer.android.com/preview/features/darktheme): Q has a system-wide dark mode that is automatically applied when in energy saving mode or via quick toggle.
    - Option A: custom dark theme (requires a lot of work but looks nice)
    - Option B: [Force Dark](https://developer.android.com/preview/features/darktheme#force_dark) "inverts" the app and we can exclude specific components. (probably doesn't look as polished as it could be)
    - Option C: Do nothing, leave it glaring white on phones with a dark UI.
- Check if we use [non-SDK interfaces](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces#test-for-non-sdk)

If someone has any additional things that we have to/should address for Q (API 29, Android 10) please feel free to comment.

**Comment by FlorentRevest** [comment]
I am obviously for switching to AndroidX, having a dark-mode and avoiding non-SDK interfaces.
I would suggest starting out with the "Force Dark" mode and then decide from there if we really need a custom dark theme.

**Comment by jrtberlin** [comment]
I've [started to implement](https://github.com/jrtberlin/AsteroidOSSync/tree/Q) the changes.
- AndroidX should be working
- the background service should work now under target/compile SDK Q too
- I started to implement the dark mode
