### ISSUE TITLE
AsteroidOSSync disables vibrate mode

### ISSUE THREAD

**Issue by Rudloff** [AsteroidOS/AsteroidOSSync#79]
Hello,

I usually keep my phone in vibrate-only mode.
But since 0.13, everytime I start AsteroidOSSync, it automatically enables my ringtone.

It is probably a side-effect of https://github.com/AsteroidOS/AsteroidOSSync/pull/68.

**Comment by jrtberlin** [comment]
Sorry, for the issue.
This was a bug in 0.12 that shouldn't be in 0.13 (It should only do anything [onConnect if you have enabled the checkbox](https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/ble/SilentModeService.java#L45))

Can you please share a few details, such as:
- Android Version
- Model number (of the phone)
- Manufacturer (of the phone)

**Comment by Rudloff** [comment]
I am using Android 7.1.2 on a Fairphone 2.

> If you still have the issue please try to enable and disable the silent mode checkbox.

This seems to have fixed the issue, thanks! (I had never enabled this option before.)

**Comment by jrtberlin** [comment]
Damn, I will try to reproduce the issue tomorrow.

**Comment by jrtberlin** [comment]
I could reproduce the issue. For some reason sometimes the Bluetooth connection resets during the pairing process and triggers the [onDisconnect()](https://github.com/AsteroidOS/AsteroidOSSync/blob/240dbb788ac552d9ec7dfbc995523351ed1af1f3/app/src/main/java/org/asteroidos/sync/ble/SilentModeService.java#L53) function. The function lacked an if statement to check if silent mode is enabled and used the fallback.
