### ISSUE TITLE
Harmony watch paired but not connected.

### ISSUE THREAD

**Issue by HeofHIShirts** [AsteroidOS/AsteroidOSSync#94]
Using 0.14 from F-Droid, I was able to pair the harmony watch (a Kingwear 88 Pro, using an MT6580 chipset) with AsteroidOS Sync exactly once, to look at the options. Every subsequent attempt to connect the watch via Bluetooth has the app find the watch (it displays "harmony"), but attempting to connect to the watch has the app say that it has trouble connecting to the watch. The watch does not show up in the list of connected bluetooth devices on my Android phone (a Pixel running Android 10), and when I ask the watch to try connecting through bluetoothctrl in a ceres session, I get back the error  "Failed to pair: org.bluez.Error.AuthenticationRejected"

The watch has stored the phone's bluetooth address and indicates that it is a paired device, so I believe the initial pairing procedure worked correctly, but it won't connect, and it won't display in the list of previously paired Bluetooth devices on my phone.

I'm not sure what the problem is, or even how to investigate further to try and figure out why the connection isn't working.

**Comment by jrtberlin** [comment]
Sorry to hear that.
A log wouldn't hurt to analyze the issue.

1. Unpair the watch via the app or delete the app data.
2. Start piping adb logcat in a text file or use the "Take bug report -> Interactive" option in "Developer options".
3. Pair the watch with the app.
4. Try to disconnect and reconnect a few times.
5. Stop the logcat command or click "Details" in the interactive bug report notification.
6. Since log files can contain data that you could consider sensitive make sure to check it before posting or send it to me directly.

**Comment by HeofHIShirts** [comment]
I have some log files. What should I be looking to pull out of them that would be most helpful to getting the information you'll need, rather than just dumping several tens of thousands of lines of messages on you?

**Comment by jrtberlin** [comment]
You can search for things like "Ble", "Bluetooth" and "org.asteroidos.sync".

**Comment by HeofHIShirts** [comment]
Great. Where should I put/send the log files with the hopefully more helpful information so you can get to them? The logcat output is about 288 lines, so I'm not sure it would do well being pasted here.

**Comment by jrtberlin** [comment]
I would use a GitHub gist or a pastebin service.

**Comment by HeofHIShirts** [comment]
Here's the gist, then. Hope it helps! 

https://gist.github.com/HeofHIShirts/69c6dbfb957673a0c37b124de889e3cf

**Comment by HeofHIShirts** [comment]
An update - between upgrading AsteroidOSSync to 0.17, flashing an April 02020 image on the watch, and/or using a trick meant to get the Bluetooth radio on Pixels working again (as a workaround to a bug with the Bluetooth), I have persistent pair and sync!

I wish I knew which of those three things is was that made it work, or what changed in the code, but whatever it is, it does work correctly now, and so I'm going to close this issue.

**Comment by jrtberlin** [comment]
Great to hear! :tada:
AsteroidOS Sync is probably not the reason it works again. We have not changed anything BLE related in quite some time.
